baseurl = "http://cloudstackcollab.org/"
languageCode = "en-us"
title = "cloudstackcollab.org"
theme = "hugo-creative-theme"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more informtion take a look at the README.

  # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
  name = "Apache CloudStack"
  description = "Apache CloudStack Collaboration Conferences"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "CloudStack Collaboration Conferences"

    [params.navigation.links]
      about     = "About"
      services  = "Why attend?"
      portfolio = "Upcomming Events"
      contact   = "Contact"


  # Hero section
  [params.hero]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "CCCNA16"
    subtitle   = "CloudOps is excited to host the first Apache CloudStack™ Collab conference of 2016 on June 1-3 2016 in beautiful Montreal, Canada."
    buttonText = "Find out more"


  # About section
  [params.about]
    headline    = "We've got what you need!"
    description = "[Apache CloudStack](http://cloudstack.apache.org) is open source software designed to deploy and manage large networks of virtual machines, as a highly available, highly scalable Infrastructure as a Service (IaaS) cloud computing platform. CloudStack is used by a number of service providers to offer public cloud services, and by many companies to provide an on-premises (private) cloud offering, or as part of a hybrid cloud solution. <br><br> Aimed at users, developers and everybody else interested in CloudStack, the CloudStack Collaboration Conference is the place to learn more about CloudStack or join developers to discuss the past, present and future. The 4th CloudStack Collaboration Conference, this event will continue with the best ideas from the previous conferences and feature a varied set of presentations. The talks and events at the conference will provide ample opportunity to meet with the CloudStack community and engage in deep discussions with developers and users. The hackathon day will provide an excellent opportunity to turn ideas into practice together with the committers and the sponsors. Watch our video to experience CloudStack Collaboration Summit."
    buttonText  = "Get started!"


  # Service section
  [params.services]
    headline = "Why attend?"

        [[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "Learn about latest features of Apache CloudStack"

        [[params.services.list]]
            icon = "fa-wrench"
            title = "Hackathon"
            description = "Participate to an Hackathon"

        [[params.services.list]]
            icon = "fa-cloud"
            title = "what about cloud?"
            description = "It's all about clouds and devops."

        [[params.services.list]]
            icon = "fa-comments-o"
            title = "Shares"
            description = "It's all about the community"

    # Aside section
  [params.aside]
    headline = "CCCNA16::Montreal"

    [params.aside.button]
      text = "Register Now"
      link = "https://www.eventbrite.ca/e/apache-cloudstacktm-conference-montreal-2016-tickets-23815552960"

    # Portfolio modals
  [params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"


  # Contact section
  [params.contact]
    headline = "Reach the community"
    description = ""
